version: '3.4'

services:
  dockerdjango:
    image: dockerdjango
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
